Add test dropping erased serializers in reverse order
    error[E0505]: cannot move out of `json_deserializer` because it is borrowed
        --> src/de.rs:1665:14
         |
    1663 |         let mut json_deserializer = serde_json::Deserializer::from_str("");
         |             --------------------- binding `json_deserializer` declared here
    1664 |         let _erased_deserializer = <dyn Deserializer>::erase(&mut json_deserializer);
         |                                                              ---------------------- borrow of `json_deserializer` occurs here
    1665 |         drop(json_deserializer);
         |              ^^^^^^^^^^^^^^^^^ move out of `json_deserializer` occurs here
    1666 |     }
         |     - borrow might be used here, when `_erased_deserializer` is dropped and runs the destructor for type `impl de::Deserializer<'_>`

    error[E0505]: cannot move out of `json_serializer` because it is borrowed
        --> src/ser.rs:1617:14
         |
    1615 |         let mut json_serializer = serde_json::Serializer::new(Vec::new());
         |             ------------------- binding `json_serializer` declared here
    1616 |         let _erased_serializer = <dyn Serializer>::erase(&mut json_serializer);
         |                                                          -------------------- borrow of `json_serializer` occurs here
    1617 |         drop(json_serializer);
         |              ^^^^^^^^^^^^^^^ move out of `json_serializer` occurs here
    1618 |     }
         |     - borrow might be used here, when `_erased_serializer` is dropped and runs the destructor for type `impl ser::Serializer`